apiVersion: v1
kind: Namespace
metadata:
    name: symfony-kubernetes-ns

---
# apiVersion: v1
# kind: Service
# metadata:
#     namespace: symfony-kubernetes-ns
#     name: symfony-service
# spec:
#     selector:
#         app: symfony
#     type: NodePort
#     ports:
#         - protocol: TCP
#           port: 8087
#           targetPort: 80
#           nodePort: 30011

apiVersion: v1
kind: Service
metadata:
    namespace: symfony-kubernetes-ns
    name: symfony-service
spec:
    selector:
        app: symfony
    type: NodePort
    ports:
        - protocol: TCP
          port: 8087
          targetPort: 80
          nodePort: 30011


---

apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: symfony-kubernetes-ns
    name: symfony-deployment
    labels:
        app: symfony
spec:
    replicas: 1
    selector:
        matchLabels:
            app: symfony
    template:
        metadata:
            labels:
                app: symfony
        spec:
            containers:
                - name: symfony
                  image: ivanaki/jenkins-example-symfony:latest
                  ports:
                      - containerPort: 80
