version: '3'

services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - '8088:80'
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - symfony
    php:
        build:
            context: ./docker/php
        environment:
            APP_ENV: dev
        volumes:
            - ./:/var/www/app
        ports:
            - '9003:9000'
        networks:
            - symfony
networks:
    symfony:
